### PR TITLE
Add ropensci scraper

### PR DESCRIPTION
**Pull request by vsoch**
This will add a scraper to parse ROpenSci repos! We determine a software repo is one based on it having a homepage (the link in the description) to a docs page on the ropensci docs site. This means we likely have a few false negatives if there is a repo that should have this URL but does not, but we are less likely to have false positives.

### CODE REVIEW

**Comment by annakrystalli** [comment]
This looks good to me and should work in most cases. I did want to mention that rOpenSci maintain a registry of active packages follow the codemeta standard in this repo: https://github.com/ropensci/roregistry. See the `registry.json` file. 

This should have most of the info needed. In any case, it is the most robust way of getting a list of current, active packages and is updated regularly and automatically.

**Comment by annakrystalli** [comment]
Sorry, I should of mentioned this yesterday! You are just too fast! 😜⚡️

Awesome work btw and many thanks for incorporating rOpenSci repos!

**Comment by vsoch** [comment]
No worries! And this is interesting - I'm seeing repos on here that aren't under ropensci (e.g., https://github.com/YuLab-SMU/treeio) is that common practice? 

I think I could probably use a combination of both approaches - the org repos API endpoint is going to be faster to get metadata for all repos in fewer calls, but then I can check against this list (and update with description, more topics). And then I'm thinking I would want to then do individual queries for the repos not on ROpenSci that are in this list.

Would that be a reasonable approach? I can come back to fix this up later today after the work day!

**Comment by annakrystalli** [comment]
> I'm seeing repos on here that aren't under ropensci (e.g., https://github.com/YuLab-SMU/treeio) is that common practice?

Well spotted! We generally discourage this but there have been exceptions where we have allowed repos not to be transfer to the rOpenSci org.

> I think I could probably use a combination of both approaches - the org repos API endpoint is going to be faster to get metadata for all repos in fewer calls, but then I can check against this list (and update with description, more topics). And then I'm thinking I would want to then do individual queries for the repos not on ROpenSci that are in this list.

> Would that be a reasonable approach? I can come back to fix this up later today after the work day!

Yup sounds totally reasonable to me. I think the key is to use the registry as the source of packages to list.

**Comment by vsoch** [comment]
okay @annakrystalli I've updated the PR here to use the registry file, and opened a new PR for the database with the repos that are found using it (plus still GitHub). https://github.com/rseng/software/pull/261

Thanks again for helping me figure this out! It was a great idea to add ropensci - can't wait to share with the community!

**Comment by annakrystalli** [comment]
No worries! Thanks for implementing so quick!

**Pull request merged**
